### ISSUE TITLE
Unknown Characters through Script

### ISSUE THREAD

**Issue by pa-0** [FlickyOs/Adobe-Debloater#3]
Hi - quick question:

Are these characters found in the batch file (that GitHub seems unable to display correctly) the result of an encoding issue, or intentional?

![image](https://github.com/user-attachments/assets/accaff02-26cf-49e8-be1b-f25c22e9971e)

**Comment by FlickyOs** [comment]
i will probably rewrite the script in python when i am free but u can ignore those characters ( they shouldn't appear they just change the text color )

**Comment by pa-0** [comment]
Yes I figured that out after posting this, but thanks for letting me know.
